# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_and_deploy_to_110.99

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployEnv
    env:
      DOCKER_ACCESS_NAME: ${{ secrets.DOCKER_ACCESS_NAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      HOST_IP_99: ${{ secrets.HOST_IP_99 }}
      HOST_ADMIN_99: ${{ secrets.HOST_ADMIN_99 }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore yarn
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: build dev
        run: ./sh/build_to_110.99.sh
      - name: deploy dev
        run: ./sh/deploy_to_110.99.sh
