# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build_dev_to_16..15

on: workflow_dispatch

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_ACCESS_NAME: ${{ secrets.DOCKER_ACCESS_NAME }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  HOST_NAME_15: ${{ secrets.HOST_NAME_15 }}
  ADMIN_HOST_15: ${{ secrets.ADMIN_HOST_15 }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore yarn
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: build dev
        run: ./sh/build_dev_to_16..15.sh
